spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: 
        data: classpath:/database/data.sql
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate.format_sql: true
            hibernate.dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
        generate-ddl: true
        hibertnate.ddl-auto: validate
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss     
# SERVER
server:
    port:8080           